### ISSUE TITLE
Error while running demo

### ISSUE THREAD

**Issue by AShlychkova** [QratorLabs/inclickdb#5]
**grafana-key logs:**
```
grafana-key_1        |   File "/usr/local/bin/pip", line 7, in <module>
grafana-key_1        |     from pip._internal import main
grafana-key_1        |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
grafana-key_1        |     from pip._internal.cli.autocompletion import autocomplete
grafana-key_1        |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
grafana-key_1        |     from pip._internal.cli.main_parser import create_main_parser
grafana-key_1        |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
grafana-key_1        |     from pip._internal.commands import (
grafana-key_1        |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
grafana-key_1        |     from pip._internal.commands.completion import CompletionCommand
grafana-key_1        |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
grafana-key_1        |     from pip._internal.cli.base_command import Command
grafana-key_1        |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 18, in <module>
grafana-key_1        |     from pip._internal.download import PipSession
grafana-key_1        |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/download.py", line 38, in <module>
grafana-key_1        |     from pip._internal.utils.glibc import libc_ver
grafana-key_1        |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/utils/glibc.py", line 3, in <module>
grafana-key_1        |     import ctypes
grafana-key_1        |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/ctypes/__init__.py", line 7, in <module>
grafana-key_1        |     from _ctypes import Union, Structure, Array
*grafana-key_1        | ImportError: Error loading shared library libffi.so.6: No such file or directory (needed by /usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so)*
grafana-key_1        | Traceback (most recent call last):
grafana-key_1        |   File "/get_key.py", line 1, in <module>
grafana-key_1        |     import requests
*grafana-key_1        | ModuleNotFoundError: No module named 'requests'*


**stand_grafana-key_1 exited with code 1**
```

**Comment by code-of-kpp** [comment]
I think the problem is with docker image been used.
Using standard `alpine` (and installing python there) or one of docker-library `python` images should help.

**Comment by mary3000** [comment]
@AShlychkova https://github.com/mary3000/inclickdb/tree/demo-fix
Here is another variant of grafana-key container, can you please try it?

**Comment by code-of-kpp** [comment]
@mary3000 could you please do that as PR? If you are not sure it works, you can mark it as draft PR.

**Comment by mary3000** [comment]
Ok, https://github.com/QratorLabs/inclickdb/pull/6
